[project]
name = "llama3"
version = "0.1.0"
description = "This is a simple toy example of a Llama 3 model implementation."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.1",
    "torch>=2.7.1",
    "torchvision>=0.22.1",
]
